### ISSUE TITLE
Please release version with fixes

### ISSUE THREAD

**Issue by anthony0030** [plashchynski/rgb#5]
Hello @plashchynski 

Last year I made this pull request https://github.com/plashchynski/rgb/pull/4
Could you please release a version ex: 0.1.1 that contains that fix so I don't need to install via a commit hash?

Many thanks for considering my request,
Anthony

**Comment by plashchynski** [comment]
Hello @anthony0030, thank you for your contribution. I've just released a new version 0.1.2 with your changes

**Comment by anthony0030** [comment]
Thank you 😄
